### ISSUE TITLE
Package does not work properly with xmpcore-6.1.x.jar

### ISSUE THREAD

**Issue by elyisgreat** [drewnoakes/metadata-extractor#402]
I'm trying to write a simple program that sorts photos by date. When I compile with xmpcore-5.1.3.jar on the classpath, the program works normally. However, when compiling with xmpcore-6.1.10.jar on the classpath, I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException
        at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(JpegMetadataReader.java:57)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:143)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:121)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:197)
        at FileDateSort.getTimestamp(FileDateSort.java:39)
        at FileDateSort.main(FileDateSort.java:57)
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
```

This seems to suggest that xmpcore is not on the classpath, when it clearly is.

What is going on here?

**Comment by Nadahar** [comment]
Metadata-extractor currently has [xmpcore 6.0.6](https://github.com/drewnoakes/metadata-extractor/blob/aa44e02372e0bae62bb9a2fe51dd9248aaca3d61/pom.xml#L68-L72) as a dependency, although I don't think a release has been made with that version. You'd have to look at what version of `xmpcore` Metadata-extractor use in the version you use, and then use that. The Java classpath system doesn't really allow mixing dependencies of different versions in the same project.

**Comment by elyisgreat** [comment]
[according to Maven](https://mvnrepository.com/artifact/com.drewnoakes/metadata-extractor/2.11.0) it seems as though version 5.1.3 is listed as a compile dependency for the latest version of metadata-extractor, so my guess is that this is the version that I should be using.

**Comment by Nadahar** [comment]
Yes, it seems like [`2.1.1` use xmpcore `5.1.3`](https://github.com/drewnoakes/metadata-extractor/blob/2.11.0/pom.xml#L69-L71), so I guess you're stuck with that version until a new release is made of Metadata-extractor.

**Comment by drewnoakes** [comment]
@elyisgreat is there something about xmpcore 6.1.10 you need that's not present in 6.0.6?

I made a release of the .NET library recently and will get a Java one out soon.

**Comment by elyisgreat** [comment]
Not really. I just assumed to download the latest version when it said that it's required. The documentation regarding xmpcore is not entirely clear about it.

**Comment by drewnoakes** [comment]
@elyisgreat I'll close this for now. I've openend #403 to track upgrading the dependency.
