### ISSUE TITLE
App Crash after upgrade 2.11.0 to 2.12.0

### ISSUE THREAD

**Issue by tumuyan** [drewnoakes/metadata-extractor#441]
the metadata-extractor 2.11.0 works ok, but when I update to 2.12.0 , the app will fc with these error log

`   // my code:
     try {
            Metadata metadata = ImageMetadataReader.readMetadata(file);
            print(metadata, "Using ImageMetadataReader");
        } catch (Exception e) {
              e.printStackTrace();
        }`

`// error log
10-02 07:47:30.660 15556-15913/com.tumuyan.filemagic W/System.err: Application uncaught exception in thread "Thread-54661" java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Point;
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.metadata.mp4.boxes.TrackHeaderBox.addMetadata(TrackHeaderBox.java:77)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.metadata.mp4.Mp4BoxHandler.processTrackHeader(Mp4BoxHandler.java:116)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.metadata.mp4.Mp4BoxHandler.processBox(Mp4BoxHandler.java:86)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:58)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.mp4.Mp4Reader.extract(Mp4Reader.java:42)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.mp4.Mp4MetadataReader.readMetadata(Mp4MetadataReader.java:57)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:178)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:125)
10-02 07:47:30.679 15556-15913/com.tumuyan.filemagic W/System.err:     at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:205)`

**Comment by payton** [comment]
This issue was fixed in #409 

Will be out in the next release!

**Comment by tumuyan** [comment]
> This issue was fixed in #409
> 
> Will be out in the next release!

thank you. 
waitting for the next release
